[package]
name = "chat_importer"
version = "0.1.0"
authors = ["DarkSky <darksky2048@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.31"
chrono = "0.4.11"
log = "0.4.8"
regex = "1.3.7"
scraper = "0.12.0"

[dependencies.gchdb]
path = "../common_chat_record"
