[package]
name = "ibackuptool2"
version = "0.1.0"
authors = ["Rich Infante <rich@richinfante.com>"]
edition = "2018"

[dependencies]
rust-crypto = "^0.2"
plist = "1.0.0"
dirs = "3.0.1"
serde_bytes = "0.11.5"
hex = "0.4.2"
ring = "0.16.20"
tempfile = "3.1.0"
wildmatch = "1.0.11"

chrono = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }

[dependencies.libsqlite3-sys]
version = "0.30.1"
features = ["bundled"]

[dependencies.uuid]
version = "0.8.1"
features = ["v4"]
