[package]
name = "chat_importer"
version = "0.1.0"
authors = ["DarkSky <darksky2048@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.92"
base64 = "0.22.1"
binread = "1.4.1"
fern = "0.7.0"
gchdb = { git = "https://github.com/darkskygit/GCHDB" }
hex = "0.4.3"
htmlescape = "0.3.1"
lazy_static = "1.5.0"
mailparse = "0.15.0"
md-5 = "0.9.1"
mur3 = "0.1.0"
num_enum = "0.7.3"
path-absolutize = "3.1.1"
path-ext = "0.1.1"
plist = "1.7.0"
rpassword = "7.3.1"
scraper = "0.12.0"
serde_json = "1.0.132"
tempfile = "3.13.0"
walkdir = "2.3.1"

chrono = { workspace = true }
ibackuptool2 = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }

[dependencies.image]
version = "0.25.4"
default-features = false
features = ["bmp", "jpeg", "png"]

[dependencies.structopt]
version = "0.3.18"
default-features = false
